export type TranscriptionMode = 'realtime' | 'whisper'

export const IPC = {
  AUDIO_START: 'audio:start',
  AUDIO_STOP: 'audio:stop',
  AUDIO_PERMISSIONS: 'audio:permissions',
  LOOPBACK_ENABLE: 'enable-loopback-audio',
  LOOPBACK_DISABLE: 'disable-loopback-audio',
  TRANSCRIPTION_START: 'transcription:start',
  TRANSCRIPTION_STOP: 'transcription:stop',
  TRANSCRIPTION_PAUSE: 'transcription:pause',
  TRANSCRIPTION_RESUME: 'transcription:resume',
  TRANSCRIPTION_CHUNK: 'transcription:chunk',
  TRANSCRIPTION_ERROR: 'transcription:error',
  SUMMARY_GENERATE: 'summary:generate',
  SESSION_LIST: 'session:list',
  SESSION_GET: 'session:get',
  SESSION_SAVE: 'session:save',
  SESSION_DELETE: 'session:delete',
  SESSION_EXPORT_MD: 'session:export-md',
  SETTINGS_GET: 'settings:get',
  SETTINGS_SET_API_KEY: 'settings:set-api-key',
  SETTINGS_SET_MODE: 'settings:set-mode',
  SETTINGS_SET_MIC_DEVICE: 'settings:set-mic-device',
  SETTINGS_SET_SYSTEM_AUDIO_SOURCE: 'settings:set-system-audio-source',
  SETTINGS_VALIDATE_API_KEY: 'settings:validate-api-key',
  SETTINGS_SET_WHISPER_MODEL: 'settings:set-whisper-model',
  SETTINGS_SET_SUMMARY_MODEL: 'settings:set-summary-model',
  SETTINGS_SET_SUMMARY_PROVIDER: 'settings:set-summary-provider',
  NATIVE_AUDIO_START: 'native-audio:start',
  NATIVE_AUDIO_STOP: 'native-audio:stop',
  NATIVE_AUDIO_SILENCE: 'native-audio:silence',
  NATIVE_AUDIO_LEVEL: 'native-audio:level',
  NATIVE_AUDIO_ERROR: 'native-audio:error',
  NATIVE_AUDIO_SUPPORTED: 'native-audio:supported',
  AUDIO_MIC_CHUNK: 'audio:mic-chunk',
  AUDIO_OUTPUT_DEVICES: 'audio:output-devices',
  AUDIO_DEFAULT_OUTPUT: 'audio:default-output',
  AUDIO_SET_OUTPUT: 'audio:set-output',
  CURATION_CURATE: 'curation:curate',
  SETTINGS_SET_CURATION_ENABLED: 'settings:set-curation-enabled',
  SETTINGS_SET_CURATION_PROVIDER: 'settings:set-curation-provider',
  SETTINGS_SET_CURATION_MODEL: 'settings:set-curation-model',
  SETTINGS_SET_CURATION_GLOSSARY: 'settings:set-curation-glossary',
  SETTINGS_GET_API_KEY_STATUS: 'settings:get-api-key-status',
  DEBUG_LOG: 'debug:log',
} as const
